name: Upload Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build python3-pip gcovr
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Build
      run: |
        ./scripts/ci_setup.sh

    - name: Run tests
      working-directory: build/${{ env.BUILD_TYPE }}
      run: |
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        gcovr -r . \
          --xml-pretty \
          -o coverage.xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v6
      with:
        files: coverage.xml
