name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies-${{ hashFiles('CMakeLists.txt') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build python3-pip

    - name: Build
      run: |
        ./scripts/ci_setup.sh

    - name: Run tests
      working-directory: build/Release
      run: |
        ctest --output-on-failure

      # TODO install
